// <auto-generated />
namespace WealthHealth.DbManagement.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class BaseInvestmentModels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BaseInvestmentModels));
        
        string IMigrationMetadata.Id
        {
            get { return "201303290141560_BaseInvestmentModels"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
